config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :posts, only: [:create, :destroy, :show] do
    resources :comments
  end

  resources :relationships,       only: [:create, :destroy]

  resources :games do
    resources :topics , only: [:show, :create, :destroy]
  end

  resources :reddits, only: [:index]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  default_scope -> { order(created_at: :desc) }
  validates :user, presence: true
  validates :post, presence: true
  validates :content, presence: true, length: { maximum: 200 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :logged_in_user, only: [:create, :destroy]

	rescue_from ActiveRecord::RecordNotFound, :with => :post_not_found

  	def post_not_found
    	flash[:info] = "Post has been deleted!"
    	redirect_to request.referrer || root_url
  	end

	def create
		@comment = Comment.new(comment_params)
		@comment.user = current_user
		if @comment.save
			flash[:success] = "Comment Posted!"
			redirect_to @comment.post
		else
			flash[:danger] = "Comment cannot be blank!"
			redirect_to @comment.post
		end
	end

	def destroy
		@comment = Comment.find(params[:post_id])
		@comment.destroy
    	flash[:success] = "Comment deleted"
    	redirect_to request.referrer || root_url
	end

	private
		def comment_params
			params.require(:comment).permit(:content,:post_id)
		end

		#Confirms the correct user.
    	def correct_user
      		@comment = Comment.find(params[:post_id])
      		redirect_to request.referrer || root_url unless current_user?(@comment.user)
    	end
	
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li id="postcomment">
  <%= link_to gravatar_for(comment.user, size: 50), comment.user.name %>
  <span class="user"><%= link_to comment.user.name, comment.user %></span>
  <span class="content"><%= comment.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(comment.created_at) %> ago.
    <% if current_user?(comment.user) %>
      <%= link_to "delete", post_comment_path(comment) , method: :delete,
                                       data: { confirm: "You sure?" } %>                            
    <% end %>
  </span>
</li>